// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnlqvxulpyazdeyuyizm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZubHF2eHVscHlhemRleXV5aXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTYyMjYsImV4cCI6MjA2NDM3MjIyNn0.KdvSiKpRPjc7QB43E6MhkfRvYaMRsNMkTWVQpP5QsTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);